export enum ControlType {
    Container = 'container',
    Wrapper = 'wrapper',
    Tabs = 'tabs',
    Group = 'group',
    Address = 'addreses',
    Datetime = 'datetime',
    Currency = 'currency',
    Dropdown = 'dropdown',
    Hidden = 'hidden',
    Percent = 'percent',
    Radio = 'radio',
    RtRw = 'rtrw',
    Textarea = 'textarea',
    Textbox = 'textbox',
    Lookup = 'lookup',
    Input = 'input',
    Template = 'template',
    Divider = 'divider',
    FormArray = 'array'
}